### PR TITLE
Lodash 4 Support

### PR DESCRIPTION
**Pull request by patrickhousley**
Changed the _.unique function call to _.uniq to provide support for Lodash v4+. Lodash removed the _.unique alias in version 4.

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
Thanks, but is there a reason for these updates? e.g. is this so contributors will not be confused by certain packages being outdated?

**Comment by patrickhousley** [comment]
The project is not compatible with the latest version of lodash because aliases were used that were removed from lodash in version 4. That is the primary reason for the PR but I figured I would also update the project dependencies while I was at it. This was done to ensure the tests were running against lodash version 4 and to resolve some deprecation messages in the npm install.

**Comment by jacksonrayhamilton** [comment]
Okay, I see that our `graceful-fs` version was deprecated, and I see that the latest `lodash` had breaking changes, but why update `lodash` in the first place? OCD? It's better somehow? I'm not necessarily opposed to updating `lodash`, but updating packages for no reason seems risky with no benefit.

**Comment by patrickhousley** [comment]
The tests would not catch the errors produced by the breaking changes in the latest version of lodash unless you use the latest version of lodash. The others were admittedly OCD.

**Comment by jacksonrayhamilton** [comment]
Okay, but the version specifier `^3.9.3` should restrict us to a version of `lodash` that works with this package. I tried `nvm use 5 && rm -rf node_modules && npm install && npm test` and saw no errors.

**Comment by patrickhousley** [comment]
You are correct but for some reason when I used it in my project, it was using the lodash being pulled in by my project instead of installing its own version of lodash. Not sure why and I figured the fastest way to fix this would be to update the vendor module (this repo).

**Comment by jacksonrayhamilton** [comment]
Interesting, I wonder why... in any case, I just need to review the changes between the new versions of `lodash` and `graceful-fs`, then we can merge this. Thank you!

**Comment by patrickhousley** [comment]
No problem. Thanks for taking a look at this.

**Pull request merged**
